minio:
  endpoint: 127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin

app:
  chunkSize: 5242880 # apparently 1MB is not possible. minimum 5MB
  uploadInChunk: false
  bucketName: "taurus-file-store"